import {dictionaryGenerator, viewDictionary} from '../../i18n/types';

export type wordsDescription = dictionaryGenerator<
  [
    'email',
    'emailInput',
    'password',
    'passwordInput',
    'forgotPassword',
    'enter',
    'register',
    'name',
    'nameInput',
    'address',
    'addressInput',
    'lastName',
    'lastNameInput',
    'phone',
    'phoneInput',
    'secondLastName',
    'secondLastNameInput',
    'back',
  ]
>;

export const registerDictionary: viewDictionary<wordsDescription> = {
  scope: 'register',
  en: {
    email: 'Email',
    emailInput: 'Enter email',
    password: 'Password',
    passwordInput: 'Enter password',
    forgotPassword: 'Forgot password?',
    enter: 'Enter',
    register: 'Register',
    name: 'Name',
    nameInput: 'Enter name',
    address: 'Address',
    addressInput: 'Enter address',
    lastName: 'Last Name',
    lastNameInput: 'Enter last name',
    phone: 'Phone',
    phoneInput: 'Enter phone',
    secondLastName: 'Second last name',
    secondLastNameInput: 'Enter second last name',
    back: 'Return',
  },
  es: {
    email: 'Email',
    emailInput: 'Ingresa tu email',
    password: 'Contraseña',
    passwordInput: 'Ingresa tu contraseña',
    forgotPassword: '¿Olvidaste tu contraseña?',
    enter: 'Entrar',
    register: 'Registrarse',
    name: 'Nombre',
    nameInput: 'Ingresa tu nombre',
    address: 'Dirección',
    addressInput: 'Ingresa tu dirección',
    lastName: 'Apellido paterno',
    lastNameInput: 'Ingresa tu apellido paterno',
    phone: 'Teléfono',
    phoneInput: 'Ingresa tu número',
    secondLastName: 'Apellido materno',
    secondLastNameInput: 'Ingresa tu apellido materno',
    back: 'Regresar',
  },
};
